stages:
  - code-compliance

vault-plain-code-compliance:
  stage: code-compliance
  image: bash:latest
  script:
    - echo "All checks passed!"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"'
